services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017

  smartpoli-backend:
    image: node:19-alpine
    working_dir: /app/packages/backend
    command: yarn start
    volumes:
      - ./:/app
    environment:
      - MONGO_URL=mongodb://root:password@mongodb:27017
    ports:
      - 5000:5000

  smartpoli-frontend:
    image: node:19-alpine
    working_dir: /app/packages/frontend
    command: yarn dev --hostname 0.0.0.0
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
      - 24678:24678
