services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017

  dev-cpe:
    image: node:19-alpine
    working_dir: /app
    command: yarn dev --hostname 0.0.0.0
    volumes:
      - ./:/app
    environment:
      - MONGO_URL=mongodb://root:password@mongodb:27017
    ports:
      - 3000:3000
