openapi: 3.0.3
info:
  title: Commercial Policies Engine
  version: 1.0.0

tags:
  - name: Authentication
    description: Routes to login and signup

paths:
  /logon:
    post:
      tags:
        - Authentication
      summary: Logon on the system.
      description: Authenticate on the system using your username and password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: joaonotfound
                  description: your unique username
                password:
                  type: string
                  description: Your password that must have at least 6 caracteres
                  example: J4gOdc%tg#
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessToken'
        '400':
          description: Bad request, missing credentials on params or blank credentials.
        '401':
          description: Account not found.
  /signup:
    post:
      tags:
        - Authentication
      summary: Create an account.
      description: Create an account and returns the access token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: joao@joao.com
                  description: your unique email
                username:
                  type: string
                  example: joaonotfound
                  description: your unique username
                password:
                  type: string
                  description: Your password that must have at least 6 caracteres
                  example: J4gOdc%tg#

      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessToken'
        '400':
          description: Bad request, missing credentials on params or blank credentials.
        '409':
          description: Duplicated username or email
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    enum: [conflict, generic]
                    example: 'conflict'
                  message:
                    type: string
                    example: 'duplicated email'

components:
  schemas:
    AccessToken:
      type: object
      properties:
        accessToken:
          type: string
